server:
 servlet:
    context-path: /gestao-despesa/api
    
springdoc:
  swagger-ui:
    path: /public/swagger
    
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-35-170-146-54.compute-1.amazonaws.com/da0324eb1t9ud8
    username: ljicypnkuwomaj
    password: 94cc7ecb4f68f4d77039038e896cb39b2480afca0633bb7fbfa4414112fc2e7c
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
